apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialcoin-flask
  namespace: socialcoin
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: ""  # TODO set  image
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: socialcoin-flask-service
  namespace: socialcoin
  labels:
    app: flask
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: flask
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: socialcoin-postgres-config
  namespace: socialcoin
  labels:
    app: socialcoin-postgres
data:
  POSTGRES_DB: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialcoin-postgres
  namespace: socialcoin
  labels:
    app: socialcoin-postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socialcoin-postgres
  template:
    metadata:
      labels:
        app: socialcoin-postgres
    spec:
      containers:
      - name: socialcoin-postgres
        image: postgres:13-alpine
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-config
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
          - name: socialcoin-postgres-storage
            mountPath: /var/lib/postgresql/db-data
      volumes:
        - name: socialcoin-postgres-storage
          persistentVolumeClaim:
            claimName: socialcoin-postgres-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: socialcoin-postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: socialcoin-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: socialcoin-postgres
